# Generated by Django 6.0.5 on 2026-06-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='complimentary',
            field=models.BooleanField(default=False, help_text='Super admin grants free permanent access'),
        ),
    ]
