# Generated by Django 6.0.5 on 2026-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g., pricing, location, services', max_length=100)),
                ('content', models.TextField(help_text='The actual details the AI should know')),
            ],
            options={
                'verbose_name_plural': 'Company Info',
            },
        ),
    ]
