# Generated by Django 6.0.5 on 2026-05-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_companyinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10),
        ),
    ]
