# Generated by Django 6.0.5 on 2026-06-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_broadcast_channel_type_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='broadcasts', to='automation.contact'),
        ),
    ]
